version: '3'

services:
  web:
    environment:
      DB_HOST: db
      PORT: 8080
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - studentNet
  db:
    image: "mongo:latest"
    volumes:
      - db-data:/data/db
    networks:
      - studentNet
      
volumes:
  db-data:

networks:
  studentNet:

